### ISSUE TITLE
Main Главное sal teparoqda qolgan ekan margin-top:20px bersak yaxshi bo'lar edi manimcha

### ISSUE THREAD

**Issue by Kholmumin** [SayramovAzizbek/Azizbek-Homework-8#2]
<img width="1379" alt="Screenshot at May 25 5-40-04 AM" src="https://user-images.githubusercontent.com/80518819/170154392-a0a03ff0-a811-4afd-adc9-ea7bc3b4b558.png">

**Comment by SayramovAzizbek** [comment]
Assalomu Aleykum, ha bu yerda В Мире tepasidan margin-top 10px bo'lib qolgan ekan, to'g'irlandi
